# Generated by Django 3.2.7 on 2021-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=350)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
