# Generated by Django 3.2.7 on 2021-09-09 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
