# Generated by Django 3.2.7 on 2021-09-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_item_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_to_sell', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
