# Generated by Django 3.2.7 on 2021-09-09 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_item_sold_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_to_sell', to=settings.AUTH_USER_MODEL),
        ),
    ]
