# Generated by Django 3.2.7 on 2021-09-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_item_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bought_by',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='item_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
